theme: jekyll-theme-minimal
title: Dr. Ulya Bayram's homepage
description: Bookmark this to keep an eye on my project updates!
---
name: Venus
discoverer: Galileo Galilei
discovered: 1610
orbit: 247 days
radius: 6051 km
tilt: 177°
---

*Venus* is the second planet from the Sun, orbiting it every 224.7 Earth days.
